name: Publish data

on:
  push:
    branches: [ main, test ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Publish
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
      - shell: bash
        env: 
          MEILI_TOKEN: ${{ secrets.MEILI_TOKEN }}
          TEST: ${{ secrets.TEST }}
        run: |
          echo test secret $TEST
          curl -s -XPUT -H "Content-Type:application/x-ndjson" \
          -H "authorization: Bearer $MEILI_TOKEN" \
          --data-binary "@./contrib.json" \
          https://search.granbestiapop.com/indexes/radio/documents